#!/bin/ksh -p

#========================================================================================#
# title           : elastic_statup                                                       #
# description     : Starting / stopping Program for 2 elastic nodes on same VM           #
# author          : Hertzog Ludovic ITEC_Dcc_Rfd_EDMS                                    #
# date            : 26/10/2018                                                           #
# version         : 1.0                                                                  #
# notes           : None                                                                 #
#========================================================================================#


#######################
#VARIABLES DECLARATIONS
#######################
USER=$(whoami)
USER_NEEDED=elasticsearch

PATH_ES_MASTER=/app/elasticsearch/elasticsearch
PATH_ES_DATA=/app/elasticsearch/elasticsearch_2
INSTANCE_MASTER=elasticsearch-6.8.7
INSTANCE_DATA=elasticsearch-6.8.7_2

HEAP_SIZE=512m             # CHOICE ALLOWED : 256m, 512m, 1g, 2g, 4g, etc

export JAVA_HOME=/usr/lib/jvm/jre
export ES_JAVA_OPTS="-Xms${HEAP_SIZE} -Xmx${HEAP_SIZE}"

###########################
# COLORS DEFINITION       
###########################
ROUGE="\\033[1;31m"        
ROUGE_SOU="\033[04;01;31m" 
ROUGE_SUR="\\033[41;38m"   
JAUNE="\\033[1;33m"        
JAUNE_SOU="\\033[04;01;33m"
JAUNE_SUR="\\033[43;30m"   
VIOLET="\\033[1;35m"       
VERT="\\033[1;32m"         
VERT_SOU="\\033[04;01;32m" 
VERT_SUR="\\033[42;30m"    
CYAN="\\033[1;36m"         
NORMAL="\\033[0;39m"       
BLACK_SOU="\\033[04;01;30m"
WHITE_SUR="\\033[47;30m"   
BLUE="\\033[1;34m"         

checkUser() {
  if [ "$USER" != "$USER_NEEDED" ]; then
    echo -e "The script must be execute with ${VERT}${USER_NEEDED}${NORMAL}"
    echo -e "Please log on with the user: ${VERT}${USER_NEEDED}${NORMAL} and retry"
    exit 1
  fi
}

checkUser $USER_NEEDED

case "$1" in
  master)
    ELK_ROLE=MASTER
    PATH_ES=${PATH_ES_MASTER} 
    PIDFILE=${PATH_ES}/pid
    INSTANCE=${INSTANCE_MASTER}
    

  ;;
  data_node)
    ELK_ROLE=DATA_NODE
    PATH_ES=${PATH_ES_DATA}
    PIDFILE=${PATH_ES}/pid
    INSTANCE=${INSTANCE_DATA}
  ;;
  *)
    echo -e "usage $0 ${CYAN}master${NORMAL}|${VIOLET}data_node${NORMAL} ${VERT}start${NORMAL}|${ROUGE}stop${NORMAL}|${BLUE}status${NORMAL}"
    exit 1
esac

status()
{
  [ -f $PIDFILE ] && pids=$(cat $PIDFILE)
  [ "$pids" ] && ps -fp $pids | grep elasticsearch.bootstrap.Elasticsearch | grep $INSTANCE 
}

status
status=$?
[ "$status" != 0 ] && rm $PIDFILE 2>/dev/null

case "$2" in
  start)
    [ $status = 0 ] && echo -e "${VERT}The Elasticsearch $ELK_ROLE node is already started.${NORMAL}" && exit 0
     $PATH_ES/bin/elasticsearch -d -p $PIDFILE 2>/dev/null
  ;;
  stop)
    [ $status = 0 ] && kill -9 $pids
    exit 0
  ;;
  status)
    exit $status
  ;;
  *)
    echo -e "usage $0 ${CYAN}master${NORMAL}|${VIOLET}data_node${NORMAL} ${VERT}start${NORMAL}|${ROUGE}stop${NORMAL}|${BLUE}status${NORMAL}"
    exit 1
  ;;
esac

