#!/bin/ksh -p

#######################
#VARIABLES DECLARATIONS
#######################
USER=$(whoami)
USER_NEEDED=elasticsearch
PATH_FILEBEAT=/apps/filebeat
PIDFILE=$PATH_FILEBEAT/pid
FILEBEAT_INSTANCE=instance

export JAVA_HOME=/usr/lib/jvm/jre

###########################
# COLORS DEFINITION       
###########################
ROUGE="\\033[1;31m"        
ROUGE_SOU="\033[04;01;31m" 
ROUGE_SUR="\\033[41;38m"   
JAUNE="\\033[1;33m"        
JAUNE_SOU="\\033[04;01;33m"
JAUNE_SUR="\\033[43;30m"   
VIOLET="\\033[1;35m"       
VERT="\\033[1;32m"         
VERT_SOU="\\033[04;01;32m" 
VERT_SUR="\\033[42;30m"    
CYAN="\\033[1;36m"         
NORMAL="\\033[0;39m"       
BLACK_SOU="\\033[04;01;30m"
WHITE_SUR="\\033[47;30m"   
BLUE="\\033[1;34m"         

checkUser() {
  if [ "$USER" != "$USER_NEEDED" ]; then
    echo -e "The script must be execute with ${VERT}${USER_NEEDED}${NORMAL}"
    echo -e "Please log on with the user: ${VERT}${USER_NEEDED}${NORMAL} and retry"
    exit 1
  fi
}

status()
{
  [ -f $PIDFILE ] && pids=$(cat $PIDFILE)
  [ "$pids" ] && ps -fp $pids | grep filebeat
}

checkUser $USER_NEEDED
status

status=$?
[ "$status" != 0 ] && rm $PIDFILE 2>/dev/null

case "$1" in
  start)
    [ $status = 0 ] && echo -e "${VERT}The filebeat $FILEBEAT_INSTANCE is already started.${NORMAL}" && exit 0
    $PATH_FILEBEAT/filebeat > /dev/null 2>&1 & echo $! > $PIDFILE
  ;;
  stop)
    [ $status = 0 ] && kill $pids
    exit 0
  ;;
  status)
    exit $status
  ;;
  *)
    echo -e "usage $0 ${VERT}start${NORMAL}|${ROUGE}stop${NORMAL}|${BLUE}status${NORMAL}"
    exit 1
  ;;
esac
